# Build:
# $ docker build --rm -f Dockerfile -t jshim/ros2_rviz .
#
# Run:
# $ rocker --x11 --nvidia --name ros2_rviz jshim/ros2_rviz
#
# Pull: (Not supported yet)
# $ docker pull jshim/ros2_rviz

FROM osrf/ros:foxy-desktop
MAINTAINER jhshim@robotis.com

CMD rviz2
