# https://github.com/gramaziokohler/ros_docker/blob/master/.github/workflows/build-ros-base.yml

name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ROS2 Gazebo / build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jshim/ros2_gazebo
        tag_with_ref: true
        path: ros2_gazebo
